Lead.create(title: "bencochrane1@me.com", status:"Hot Lead")
Lead.create(title: "bencochrane2@me.com", status:"Cold Lead")
Lead.create(title: "bencochrane3@me.com", status:"Warm Lead")
Lead.create(title: "bencochrane4@me.com", status:"Cold Lead")
Lead.create(title: "bencochrane5@me.com", status:"Hot Lead")