Lead.create(title: "bencochrane1@me.com", status_id: 1)
Lead.create(title: "bencochrane2@me.com", status_id: 2)
Lead.create(title: "bencochrane3@me.com", status_id: 3)
Lead.create(title: "bencochrane4@me.com", status_id: 4)
Lead.create(title: "bencochrane5@me.com", status_id: 5)